[build]
  command = "npm run postinstall && npm run build-netlify"
  functions = "functions"
  publish = "dist"

[dev]
  command = "npm run serve"
  publish = "src"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
